### ISSUE TITLE
Numpy and Torch Dependencies

### ISSUE THREAD

**Issue by gabuzi** [mmuckley/torchkbnufft#104]
Hi,

Thanks for the new releases!

I saw that the >= v1.5.0 releases require torch >= 2.0. Has there been any change related to #98?

Similarly, I saw the >= 1.5.2 require numpy >= 2.0. I just quickly checked the diffs of the new releases, but couldn't spot any change that makes the package incompatible with the 1.x numpy (I might have missed it).

**Comment by mmuckley** [comment]
Hello @gabuzi, I ran some tests offline and found that older versions of numpy caused some errors, so I decided to bump up requirements to the latest just to be safe, as well as torch 2.0.

Users can always ignore dependencies on installation if they want to try to use an older numpy, or if there are errors, they can also select 1.4 of `torchkbnufft` (which is almost exactly the same as 1.5).

**Comment by gabuzi** [comment]
I see, thanks for clarifying!
I was looking at this from the conda side, preparing the new release and was considering potential impact and wasn't quite sure. As you say, 1.4 of course remains available, which the solver will automatically fall back to in case of some other dependency prohibiting torch 2.0 or numpy 2.0.

**Comment by mmuckley** [comment]
Closing as this does not document a bug.
