### ISSUE TITLE
Is it possible to use *cfl files with this library?

### ISSUE THREAD

**Issue by mscipio** [mmuckley/torchkbnufft#37]
Hello,
I am aware this is a very specific question, but I will try, and if you think this is not the setting for such a discussion feel free to lock the issue.

So, I am trying to use this library to reconstruct real MRI data acquired on a Siemens mMR scanner.
For that purpose I am able to use 2 different data export formats:

- meas*_.dat files (which I can decode using mapvbvd)
- *.cfl file (which I can decode using a function integrated in BART)

Decoding the .dat file, and writing the trajectory myself as a python function worked for a radial stack-of-stars sequence, and I am able to get nice images using your library.

For a SpiralVIBE UTE, instead, I was trying to decode those cfl files, as I don't exactly know how to code the trajectory myself. Decoding those files give me both the kspace data and the trajectory.

However, the shape of the arrays I get from those .cfl files is most likely not suited for what tkbn expects me to feed to the nufft operator and needs to be tweaked. The issue is that I am failing to understand how to do it in the correct way.

The original shape of those arrays is:

- **kspace**: (580, 296, 160, 20) 
- **ktraj** :(3, 580, 296, 160)

without any reshape or transposition, I always get an error saying: `ValueError: If omega has batch dim, omega batch dimension must match data`

I have tried all sorts of transpositions with no success. Even trying to unsqueeze the kspace array gives the same error.

The only solution that 'works' is when I unravel both arrays to:
- **kspace**: [1, 1, 27468800]
- **ktraj** :[3, 27468800]

But even in this case, the images I get inverting the kspace are just a 'point' in the center. of the FOV.

I was wondering if you had tried working with a similar type of 3D spiral trajectory and could me any tip about how to organize those arrays before using them as input for the nufft operator.

Thank you!

**Comment by mmuckley** [comment]
Hello @mscipio, could you describe what your dimensions mean? To me it looks like a 20-coil dataset. As you can see from the [KbNufftAdjoint documentation](https://github.com/mmuckley/torchkbnufft/blob/f7f5fb69d01433e433f266fbf9006330acf6d1db/profile_torchkbnufft.py#L215-L220) the input size should be `(N, C) + klength`, where `N` is the batch size and `C` is the number of coils, so I think your inputs should be `[1, 20, 44636800]` for the data and `[3, 44636800]` for the trajectory.

Also from the documentation, the units of the k-space should be in radians/voxel, so there may be some conversions you need for the trajectory before inputting it into the operator.

Lastly, I'll say that the package can be a little slow with 3D trajectories, as stated in the [performance notes](https://torchkbnufft.readthedocs.io/en/stable/performance.html). If there are any transformations you can make to a 2D problem (e.g., a stack-of-stars radial trajectory), I highly recommend using those to improve computation speed.

**Comment by mmuckley** [comment]
Closing as there has been no follow-up. Feel free to reopen if necessary.
