### ISSUE TITLE
ToepNufft's scale is inconsistent with KbNufft when norm = 'ortho' and grid size != 2*im_size

### ISSUE THREAD

**Issue by guanhuaw** [mmuckley/torchkbnufft#38]
Hi Matthew,
Thanks for such an elegant implementation for NUFFT on Pytorch.
I have on little question: when choosing 'ortho' norm and the grid_size is not exactly 2*im_size, the scale of ToepNUFFT is inconsistent with AdjKbNufft(KbNufft()). This also happens before 1.0.0. 
Thanks in advance.

**Comment by mmuckley** [comment]
Hello @guanhuaw, thanks for bringing this up. Are the values consistent without the use of `norm="ortho"`?

**Comment by guanhuaw** [comment]
Thanks! When the norm = None, the values are consistent under my test cases.

**Comment by mmuckley** [comment]
@guanhuaw PR #39 should fix this. Would you be willing to review it and try it on your use case?

**Comment by mmuckley** [comment]
I'm going to go ahead and merge. If you encounter issues with the new version please let me know.

**Comment by guanhuaw** [comment]
Hi @mmuckley  thanks for the update!
When testing with the latest commit, it seems that `norm = None` or `norm = 'ortho'` will produce the same results for the ToepNufft module, deviant from v1.2. My guess is that the updated `calc_toeplitz_kernel` function causes this problem.

**Comment by mmuckley** [comment]
Hello @guanhuaw could you clarify the problem? I don't understand your message.

**Comment by guanhuaw** [comment]
Thanks! The results are exactly the same for  `norm = None` or `norm = 'ortho`' scenarios, and there is no scaling factor between the two.
