### ISSUE TITLE
faster cal_density_compensation_function?

### ISSUE THREAD

**Issue by wenqihuang** [mmuckley/torchkbnufft#45]
Hi @mmuckley, 

thank you for the great job for non-Cartesian MR reconstruction!

I'm currently working on cardiac MRI with radial acquisition. I found that the computation of density compensation takes much longer time than the `nufft` itself. Would it be possible to speed it up? Or any suggestions on that?

Thanks in advance!

**Comment by mmuckley** [comment]
Hello @wenqihuang, you can reduce the [number of iterations](https://github.com/mmuckley/torchkbnufft/blob/fc45de889895b288bc1163ebefa303a3fe4cc362/torchkbnufft/_nufft/dcomp.py#L13). 10 is definitely erring on the side of accuracy and is probably too many.

**Comment by wenqihuang** [comment]
Thanks @mmuckley, it's faster now.
