### ISSUE TITLE
Issue with batched toeplitz kernels

### ISSUE THREAD

**Issue by andrewwmao** [mmuckley/torchkbnufft#46]
Hey Matt, I seem to be consistently getting an error when attempting to call "calc_toeplitz_kernel" with 'omega' with dimension (N, 3, klength) and 'weights' with dimension (N, 1, klength). This seems to occur even when N=1. The error goes away if I simply don't supply the density compensation weights. Any suggestions for how to fix?

![error_msg](https://user-images.githubusercontent.com/9981070/146232839-8c262479-9305-412c-bd72-8cd3df9ac089.png)

**Comment by mmuckley** [comment]
I will probably need to look into this a bit, but it seems like a batching issue.

**Comment by andrewwmao** [comment]
I should also mention -- the calculation works if N=1, I unsqueeze the batch dimension from k but not from dcomp. Not sure if this is expected behavior.

**Comment by mmuckley** [comment]
More evidence for a batching issue!

**Comment by mmuckley** [comment]
Hello @andrewwmao, I created #53 and didn't find an issue with current package operation. Could you have a look at the test and see if there are any changes I need to have it match your use case?

**Comment by mmuckley** [comment]
What version of PyTorch are you using? It seems I'm currently testing with 1.10. https://github.com/mmuckley/torchkbnufft/blob/main/requirements.txt

**Comment by andrewwmao** [comment]
I'm also using version 1.10. Right now I am just calling the function in a loop for better memory efficiency with large N, so I'm not too invested in tracking down the discrepancy at the moment. Thanks for your help!

**Comment by mmuckley** [comment]
Okay I am going to merge #53 for now and close this issue. If you encounter it in the future feel free to open up a new issue with further details.
