### ISSUE TITLE
data range changed after processing

### ISSUE THREAD

**Issue by bigponglee** [mmuckley/torchkbnufft#72]
For example, in the provided code example [Toeplitz Example](https://colab.research.google.com/github/mmuckley/torchkbnufft/blob/main/notebooks/Toeplitz%20Example.ipynb)，you can find that:
![image](https://user-images.githubusercontent.com/43057237/185734036-f68c49dc-62cf-44f8-881d-dbaae34bd91e.png)
After applying the nufft operation, the range of the data has changed a lot. Although it is possible to force the unification of the data range through data normalization, how to normalize itself is still debatable.

**Comment by mmuckley** [comment]
Hello @bigponglee, this is entirely expected. By using the NUFFT you are applying a coordinate transformation to an integral without using the Jacobian to normalize the new unit of integration. There are methods such as [density compensation]([https://doi.org/10.1002/(SICI)1522-2594(199901)41:1<179::AID-MRM25>3.0.CO;2-V](https://doi.org/10.1002/(SICI)1522-2594(199901)41:1%3C179::AID-MRM25%3E3.0.CO;2-V)) to partially, but not completely compensate for the effect.

**Comment by wenqihuang** [comment]
Hi @mmuckley, 
thanks for the explanation! I'm also encountering this problem and using an ugly operator normalization to imperfectly fix it. Would you share some papers you mentioned as density compensation? It would be very helpful! Many thanks!
Best,
Wenqi

**Comment by mmuckley** [comment]
@wenqihuang several people use this paper as a reference: https://onlinelibrary.wiley.com/doi/abs/10.1002/(SICI)1522-2594(199901)41:1%3C179::AID-MRM25%3E3.0.CO;2-V
